accounts/passwords/urls.py
# accounts.passwords.urls.py
from django.urls import path, re_path
# from django.contrib.auth import views as auth_views

from accounts.views import (
                         password_change,
                         password_change_done,
                         password_reset,
                         password_reset_done,
                         password_reset_confirm,
                         password_reset_complete,



                         )

app_name = "passwords"


urlpatterns  = [
                re_path(r'^password/change/$',
                        password_change,
                        name='password_change'),
                re_path(r'^password/change/done/$',
                        password_change_done,
                        name='password_change_done'),

                re_path(r'^password/reset/$',
                        password_reset,
                        name='password_reset'),
                re_path(r'^password/reset/done/$',
                        password_reset_done,
                        name='password_reset_done'),


                path('password/reset/<uidb64>/<token>/',
                        password_reset_confirm,
                        name='password_reset_confirm'),

                re_path(r'^password/reset/complete/$',
                        password_reset_complete,
                        name='password_reset_complete'),
        ]

accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import LogoutView


from .views import (
		# login_page,
		# register_page,

		account_home_view,
		# View based Class
		LoginView,

		AccountHomeView,

		AccountEmailActivateView,

		UserDetailUpdateView,

		register,

			)

app_name = "accounts"





urlpatterns = [

	     path("login/", LoginView.as_view(), name="login"),
	     path("register/", register, name="register"),

		 path("logout/", LogoutView.as_view(), name="logout"),

	     path("", account_home_view, name="home"),

	     re_path(r'^email/confirme/(?P<key>[0-9A-Za-z]+)/$', AccountEmailActivateView.as_view(), name="email_activate"),

	     path("email/resend-activation", AccountEmailActivateView.as_view(), name="resend_activation"),
	     path("update", UserDetailUpdateView.as_view(), name="user_update"),





]

flex/urls.py
from django.urls import re_path, path

from .views import (

			about,
			GenerateLesCodePdf
			)








app_name = "flex"





urlpatterns = [

		path("about", about, name="about"),



		]

ylla_consulting/urls.py
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

urlpatterns = [
    path('yalla-consulting-admin/', admin.site.urls),

        path('account/', include("accounts.urls", namespace="accounts")),
        path('accounts/', include("accounts.passwords.urls", namespace="passwords")),




    # Pour wagtail
        re_path(r'^admin/', include(wagtailadmin_urls)),
        re_path(r'^documents/', include(wagtaildocs_urls)),
]



if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    re_path(r"", include(wagtail_urls)),
]

home/models.py
from django.db import models
from django import forms
from django.shortcuts import render
from django.db.models.signals import pre_save


from modelcluster.fields import ParentalKey

from wagtail.core.models import Page, Orderable
from wagtail.admin.edit_handlers import (
                                FieldPanel, PageChooserPanel,
                                StreamFieldPanel, InlinePanel,
                                MultiFieldPanel,
                                ObjectList, TabbedInterface,
                                FieldRowPanel,
                                )
from wagtail.core.fields import RichTextField,  StreamField
from wagtail.snippets.edit_handlers import SnippetChooserPanel

from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.core import blocks as streamfield_blocks

from wagtail.contrib.routable_page.models import RoutablePageMixin, route


#Local import
from core import blocks
from utils.generator_utils import unique_slug_generator




# Create your models here.




class Home(RoutablePageMixin, Page):
    template = "home.html"
    subpage_types = ["flex.About"]
    max_count = 1
    parent_page_types = ["wagtailcore.Page"]
    class Meta:
        verbose_name = "Accueil"
        verbose_name ="Accueil"


    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request, *args, **kwargs)
        carousels = Carousel.objects.filter(affiche=True)
        context["carousels"] = carousels
        return context


Home._meta.get_field("title").verbose_name ="Titre"



class Carousel(models.Model):

	image 		    = models.ForeignKey("wagtailimages.Image", null=True, blank=False, on_delete=models.SET_NULL, related_name="+")
	title 		    = models.CharField("Titre", max_length=200, blank=True, null=True, help_text="Ajouter un titre")
	sub_title 	    = models.CharField("Sous titre", max_length=250, blank=True, null=True, help_text="Ajouter un sous-titre")
	link_text       = models.CharField("Texte du lien", max_length=200, blank=True, null=True, help_text="Ajouter le texte du lien")
	affiche         = models.BooleanField(default=True)




	class Meta:
		verbose_name = "Carousel"
		verbose_name_plural = "Carousels"


	def __str__(self):
		return "Carousel {title}".format(title=self.title)




	panels = [
	ImageChooserPanel("image"),
	FieldRowPanel([
		FieldPanel("title", classname="col6"),
		FieldPanel("sub_title", classname="col6"),

        FieldPanel("link_text", classname="col6"),
		]),

		FieldPanel("affiche", widget=forms.CheckboxInput),

	]

accounts/views.py
import warnings

from django.conf import settings

from django.http import HttpResponse, HttpResponseRedirect, QueryDict

from django.template.response import TemplateResponse

from django.views.generic import CreateView, FormView, DetailView, View, UpdateView
from django.views.generic.edit import FormMixin

from django.shortcuts import render, redirect, resolve_url

from django.urls import reverse, reverse_lazy

from django.utils.deprecation import RemovedInDjango40Warning
from django.utils.http import is_safe_url, urlsafe_base64_decode
from django.utils.decorators import method_decorator
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _

from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth import  (
                    authenticate,
                    login, get_user_model,
                    logout,
                    update_session_auth_hash,

                    )
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.cache import never_cache




#Local import

from ylla_consulting.mixins import NextUrlMixin, RequestFormAttachMixin

from .signals import user_logged_in

from .models import  EmailActivation

from .forms import (

			LoginForm,
			RegisterForm,


			PasswordChangeForm,
			PasswordResetForm,
			SetPasswordForm,
            ReactivateEmailForm,
            UserDetailUpdateForm,

	)



User =get_user_model()


# Create your views here.






@login_required
def account_home_view(request):
	return render(request, "accounts/home.html", {})


@method_decorator(login_required, name='dispatch') # ça peut marcher si on veux rediriger l'utilisateur sur la page de connexion
class AccountHomeView(DetailView):
	template_name = "accounts/home.html"

	def get_objet(self):
		return self.request.user



class AccountEmailActivateView(FormMixin,View):
    success_url = reverse_lazy("accounts:login")
    form_class = ReactivateEmailForm
    key = None
    def get(self, request, key=None, *args, **kwargs):
        self.key = key
        if key is not None:
            qs = EmailActivation.objects.filter(key__iexact=key)
            confirm_qs = qs.confirmable()
            if confirm_qs.count() == 1:
                obj = confirm_qs.first()
                obj.activate()
                messages.success(request, _("Votre adresse émail a été confirmé avec succès. Vous pouvez vous connecté en toute sécurité"))
                return redirect ("accounts:login")

            else:
                activated_qs = qs.filter(activated=True)
                if activated_qs.exists():
                    reset_link = reverse("passwords:password_reset")
                    msg = _("""
                            Votre adresse émail a déjà été confirmée;
                           Avez vous besoin de <a href="{link}"> reinitialiser votre mot de passe </a>?

                          """.format(link=reset_link))
                    messages.success(request, mark_safe(msg))
                    return redirect ("accounts:login")


        context= {"form": self.get_form(), "key":key}
        #if activated
        #retrurn redirect
        # if already activated
        # return redirect
        # if error return this
        return render(request, "accounts/registration/activation_error.html", context)


    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)

        else:
            return self.form_invalid(form)


    def form_valid(self, form):
        msg = _(""" Lien d'activation a été envoyé, Veillez vérifier votre boite mail. N'hésitez pas à vérifier vos spam on ne sait jamais""")
        request = self.request
        messages.success(request, msg)
        email = form.cleaned_data.get("email")
        obj = EmailActivation.objects.email_exists(email).first()
        user = obj.user
        new_activation = EmailActivation.objects.create(user=user, email=email)
        new_activation.send_activation_email()
        return super(AccountEmailActivateView, self).form_valid(form)



    def form_invalid(self, form):
        context = {"form": form, "key": self.key}
        return render(self.request, "accounts/registration/activation_error.html", context)


def register(request):
    form = RegisterForm(request.POST or None)
    phone_input = request.POST.get("phone_input")
    terms_check = request.POST.get("terms_check")

    if form.is_valid() and phone_input and terms_check is not None:
        instance = form.save(commit=False)
        instance.mobile= phone_input
        instance.save()

        msg = _(""" Lien d'activation a été envoyé,veillez vérifier votre boite mail. N'hésitez pas à vérifier vos spam, on ne sait jamais""")
        messages.success(request, msg)
        return redirect("accounts:login")
    context = {
        "form": form
    }

    return render(request, "accounts/register.html", context)






class LoginView(NextUrlMixin, RequestFormAttachMixin, FormView):
    form_class = LoginForm
    # success_url = "/"
    template_name = "accounts/login.html"

    def form_valid(self, form):
        next_path = self.get_next_url()
        return redirect(next_path)

    def get_success_url(self):
        return self.get_next_url()



@method_decorator(login_required, name='dispatch') # ça peut marcher si on veux rediriger l'utilisateur sur la page de connexion
class UserDetailUpdateView(UpdateView):
    form_class = UserDetailUpdateForm
    template_name = "accounts/detail_update_view.html"

    def get_object(self):
        return self.request.user



    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailUpdateView, self).get_context_data(*args, **kwargs)
        context["title"] = _("Modifier les détails de votre compte")
        return context


    def get_success_url(self):
        return reverse("accounts:home")


# 4 views for password reset:
# - password_reset sends the mail
# - password_reset_done shows a success message for the above
# - password_reset_confirm checks the link the user clicked and
#   prompts for a new password
# - password_reset_complete shows a success message for the above

@csrf_protect
def password_reset(request,
                   template_name='accounts/registration/password_reset_form.html',
                   email_template_name='accounts/registration/password_reset_email.html',
                   subject_template_name='accounts/registration/password_reset_subject.txt',
                   password_reset_form=PasswordResetForm,
                   token_generator=default_token_generator,
                   post_reset_redirect=None,
                   from_email=None,
                   extra_context=None,
                   html_email_template_name=None,
                   extra_email_context=None):
    warnings.warn("The password_reset() view is superseded by the "
                  "class-based PasswordResetView().",
                  RemovedInDjango40Warning, stacklevel=2)
    if post_reset_redirect is None:
        post_reset_redirect = reverse('passwords:password_reset_done')
    else:
        post_reset_redirect = resolve_url(post_reset_redirect)
    if request.method == "POST":
        form = password_reset_form(request.POST)
        if form.is_valid():
            opts = {
                'use_https': request.is_secure(),
                'token_generator': token_generator,
                'from_email': from_email,
                'email_template_name': email_template_name,
                'subject_template_name': subject_template_name,
                'request': request,
                'html_email_template_name': html_email_template_name,
                'extra_email_context': extra_email_context,
            }
            form.save(**opts)
            return HttpResponseRedirect(post_reset_redirect)
    else:
        form = password_reset_form()
    context = {
        'form': form,
        'title': _('Password reset'),
    }
    if extra_context is not None:
        context.update(extra_context)

    return TemplateResponse(request, template_name, context)


def password_reset_done(request,
                        template_name='accounts/registration/password_reset_done.html',
                        extra_context=None):
    warnings.warn("The password_reset_done() view is superseded by the "
                  "class-based PasswordResetDoneView().",
                  RemovedInDjango40Warning, stacklevel=2)
    context = {
        'title': _("L'initialisation du mot de passe envoyée"),
    }
    if extra_context is not None:
        context.update(extra_context)

    return TemplateResponse(request, template_name, context)


# Doesn't need csrf_protect since no-one can guess the URL
@sensitive_post_parameters()
@never_cache
def password_reset_confirm(request, uidb64=None, token=None,
                           template_name='accounts/registration/password_reset_confirm.html',
                           token_generator=default_token_generator,
                           set_password_form=SetPasswordForm,
                           post_reset_redirect=None,
                           extra_context=None):
    """
    Check the hash in a password reset link and present a form for entering a
    new password.
    """
    warnings.warn("The password_reset_confirm() view is superseded by the "
                  "class-based PasswordResetConfirmView().",
                  RemovedInDjango40Warning, stacklevel=2)
    assert uidb64 is not None and token is not None  # checked by URLconf
    if post_reset_redirect is None:
        post_reset_redirect = reverse('passwords:password_reset_complete')
    else:

home/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/accounts/detail_update_view.html
{% extends "base.html" %}
{% load static %}

{% block title %}

<title>AmbaGuiRabat:Modification du profile</title>

{% endblock title %}

{% block content %}
<div class="container">

	<div class="col-12 col-md-6 mx-auto">
		{% if title %}
			<h1 class="my-3">{{ title }}</h1>
		{% endif %}

		<form method="POST" action=" {% if action_url %}{{ action_url }}{% endif %}">
			{% csrf_token %}
			{% if next_url %}
			<input type="hidden" name="next" value="{{ next_url }}">

			{% endif %}

			{{ form.as_p }}
			<label for="email">Email</label>
			<input id="email" type="text" class="form-control" value="{{ request.user.email }}" disabled="disabled"><span class="help-text">Le mail ne peut pas être changerC</span><br>

			<button type="submit" class="btn btn-default my-3">Save</button> <br>
			<a href="{% url 'passwords:password_change' %}">Changer le mot de passe</a>
		</form>
	</div>




</div>
{% endblock content %}

accounts/templates/accounts/home.html
{% extends "base.html" %}

{% load static %}

{% block title %}

<title>Yllo Consulting:Utilisateur</title>

{% endblock title %}

{% block content %}
<div class="container">


	<div class="row">
		<div class="col-12">
			<h1>Compte</h1>
		</div>


		<div class="col-12 col-md-3 col-lg-3 col-sm-4 my-3">
			<div class="card">
			  <div class="card-body">
			    <h4 class="card-title">Support</h4>
			    <div class="list-group">
			    	<a class="list-group-item" href="{% url 'about' %}">A propos de nous </a>

			    	<a class="list-group-item" href="{% url 'contact' %}">Contact </a>
			    	<a class="list-group-item" href="{% url 'analytics:sales_analytics' %}">Analyse des vente </a>


			 	</div>
			  </div>
			</div>
		</div>


		<div class="col-12 col-md-3 col-lg-3 col-sm-4 my-3" id="billing">
			<div class="card">
			  <div class="card-body">
			    <h4 class="card-title">Billing</h4>

			    <div class="list-group">
			    	<a class="list-group-item" href="{% url 'orders:list' %}">Orders </a>
			    	<a class="list-group-item" href="{% url 'billing:billing_payment_method' %}">Payment method </a>
			    	<a class="list-group-item" href="{% url 'about' %}">Addresses </a>


			 	</div>


			  </div>
			</div>
		</div>


		<div class="col-12 col-md-3 col-lg-3 col-sm-4 my-3">
			<div class="card">
			  <div class="card-body">
			    <h4 class="card-title">Détails du compte</h4>

			    <div class="list-group">
			    	<a class="list-group-item" href="{% url 'accounts:user_update' %}">Mettre à jour les détails</a>

			    	<a class="list-group-item" href="{% url 'passwords:password_change' %}">Changer de mot de passe</a>

			    	<a class="list-group-item" href="{% url 'library' %}">Votre librairie</a>


			 	</div>


			  </div>
			</div>
		</div>



		<div class="col-12 col-md-3 col-lg-3 col-sm-4 my-3">
			<div class="card">
			  <div class="card-body">
			    <h4 class="card-title">Preference</h4>

			    <div class="list-group">
			    	<a class="list-group-item" href="{% url 'marketing:marketing_pref' %}">Email marketing preference</a>

			 	</div>


			  </div>
			</div>
		</div>




		<div class="col-12 col-md-3 col-lg-3 col-sm-4 my-3">
			<div class="card">
			  <div class="card-body">
			    <h4 class="card-title">Historiques</h4>

			    <div class="list-group">
			    	<a class="list-group-item" href="{% url 'products:user_history' %}">Les produits</a>
			 	</div>


			  </div>
			</div>
		</div>





	</div>


</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load static %}




<title>
    {% block title %}
       Connexion
    {% endblock %}
    {% block title_suffix %}
        -Ylla Consulting
    {% endblock %}
</title>


{% block content %}
<div class="container">


    <div class="row centered-form">
        <div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
	          <div class="panel panel-default" style="text-align: center;">
		            <div class="panel-heading">
		              <h3 class="panel-title center">Se Connecter</h3>
		            </div>

		            <div class="panel-body">
			         	 <form method="POST" role="form" >
			                {% csrf_token %}

			             	<div class="row">
			                  	<div class="col-xs-12 col-sm-12 col-md-6">
			                  	  	<div class="form-group">
										{{ form.email.label }}
										{{ form.email }}
										{% if form.email.errors %}
											<small style="color: red">{{ form.email.erros }}</small>
										{% endif %}
									</div>
								</div>
								<div class="col-xs-12 col-sm-12 col-md-6">
		                <div class="form-group">
  										{{ form.password.label }}
  										{{ form.password }}
  										{% if form.password.errors %}
  											<small style="color: red">{{ form.password.erros }}</small>
  										{% endif %}

					         </div>
								</div>

                <div class="col-xs-12 col-sm-12 col-md-6">


									<p><a href="{% url 'passwords:password_reset' %}">Mot de passe oublié ?</a></p>
								</div>
							</div>



							<button type="submit" class="btn btn-info btn-block">Connexion</button>

						</form>
					</div>
					<div class="col">
						<h4>Pas encore de compte ?</h4>
						<p><a href="{% url 'accounts:register' %}" class="btn btn-primary">Créer un compte gratuitement</a></p>
					</div>

				</div>
		</div>
	</div>



</div>
{% endblock content %}

accounts/templates/accounts/register.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Enregistrement
{% endblock %}




{% block extra_static %}

{% endblock extra_static %}

{% block content %}


<div class="container">

      <div class="row centered-form">
        <div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
          <div class="panel panel-default" style="text-align: center;">
            <div class="panel-heading">
              <h3 class="panel-title">Créer un pour avoir une meilleure expérience de nos services</h3>
            </div>

            <div class="panel-body">

                <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                 {% if messages %}
                                        {% for message in messages %}
                                            {% if message.tags == 'success' %}
                                                <div class="alert alert-success">{{ message }}</div>
                                            {% elif message.tags == 'error' %}
                                                <div class="alert alert-danger">{{ message }}</div>
                                            {% endif %}
                                        {% endfor %}
                                 {% endif %}
                            </div>
                        </div>
                </div>
                 	 <form method="post" role="form" class="register-form-ajax" action="{% url 'accounts:register' %}" data-endpoint="{% url 'accounts:register' %}">
	                    {% csrf_token %}


	                 	 <div class="row">
	                      	<div class="col-xs-12 col-sm-12 col-md-6">
	                      	  <div class="form-group">

									{{ form.email.label }}
									{{ form.email }}
									{% if form.email.errors %}
										<small style="color: red">{{ form.email.errors }}</small>
									{% endif %}

								</div>
							</div>

							<div class="col-xs-12 col-sm-12 col-md-6">

	                      	  	<div class="form-group">
	                      	  		<label style="display: block;
    												font-weight: initial;
    												width: -webkit-fill-available; ">Téléphone</label>
									<input id="phone" type="tel" class="form-control input-xs" name="phone" required>
									<span id="valid-msg" class="hide">✓ Valid</span>
									<span id="error-msg" class="hide"></span>
									<input  name="phone_number[phone_input]" type="hidden">



								</div>



							</div>


						</div>


						 <div class="row">
	                      	<div class="col-xs-12 col-sm-12 col-md-6">
		                      	  <div class="form-group">

									{{ form.password1.label }}
									{{ form.password1 }}
									{% if form.password1.errors %}
										<small style="color: red">{{ form.password1.errors }}</small>
									{% endif %}
						    		<span id="aideMdp"></span>
						    	</div>
					    	</div>

					    	<div class="col-xs-12 col-sm-12 col-md-6">
	                      	  	<div class="form-group">
									{{ form.password2.label }}
									{{ form.password2 }}
									{% if form.password2.errors %}
										<small style="color: red">{{ form.password2.errors }}</small>
									{% endif %}
								</div>
							</div>
						</div>
						<div class="row">
							<div class="form-group">
								<p>Vous avez déjà un compte ? <a href="{% url 'accounts:login' %}">Connectez-vous</a></p>
							    <div class="form-check">
							      <input class="form-check-input" type="checkbox"  name="terms_check" value="" id="invalidCheck2" required>
							      <label class="form-check-label" for="invalidCheck2">
							        En envoyant vous acceptez <a href="#" style="color: darkblue; ">les conditions d'utilisation</a>
							      </label>
							    </div>
							 </div>
						</div>

						<button type="submit" class="btn btn-info btn-block">Envoyer</button>
					 </form>
				</div>
			</div>
		</div>
	</div>



</div>




{% endblock content %}



{% block extrat_js %}

<link rel="stylesheet" href="{% static 'css/intlTelInput.css' %}">


<script type="text/javascript" src="{% static 'js/intlTelInput.js' %}"></script>


<script type="text/javascript">

	//Vérification de la longueur du mot de passe saisi
	document.getElementById("controleMdpSaisi").addEventListener("input", function(e){
		var mdp = e.target.value;//Valeur saisie dans le champ mdp
		var longueurMdp = "faible";
		var couleurmsg = "red";//Longueur faible=>couleur rouge
		if(mdp.length>=8){
			longueurMdp = "Suffisante";
			couleurmsg="green";//Longueur suffisante=>couleurmsg verte
		}
		else if(mdp.length>=4){
			longueurMdp = "moyenne";
			couleurmsg = "orange";//Longueur moyenne=>couleurmsg orange
		}

		var aideMdpElt = document.getElementById("aideMdp");
		aideMdp.textContent="Longueur : " + longueurMdp; //Texte de l'aide
		aideMdp.style.color = couleurmsg;//Couleur du texte de l'aide
	});



			$(document).ready(function(){

								var input = document.querySelector("#phone"),
									errorMsg = document.querySelector("#error-msg"),
							validMsg = document.querySelector("#valid-msg");

							// here, the index maps to the error code returned from getValidationError - see readme
					var errorMap = ["Nombre invalide", "Code de pays invalide", "Trop court", "Trop long", "Nombre invalide"];

					// initialise plugin
					var iti = window.intlTelInput(input, {
						initialCountry: "MA",
									separateDialCode: true,
									hiddenInput: "phone_input",
									geoIpLookup: function(callback) {
										$.get('https://ipinfo.io', function() {}, "jsonp").always(function(resp) {
											var countryCode = (resp && resp.country) ? resp.country : "";
											callback(countryCode);
										});
									},
									utilsScript: "{% static 'js/tel-input-utils.js' %}"
					});

					var reset = function(){
						input.classList.remove("error");
						errorMsg.innerHTML = "";
						errorMsg.classList.add("hide");
						validMsg.classList.add("hide")
					};

					//on blur: validate
					input.addEventListener('blur', function() {
						reset();
						if(input.value.trim()){
							if(iti.isValidNumber()){
								validMsg.classList.remove("hide")
							}else{
								input.classList.add("error");
								var errorCode = iti.getValidationError();
								errorMsg.innerHTML = errorMap[errorCode];
								errorMsg.classList.remove("hide")
							}
						}
					});
					//on keyup /change flag: reset
					input.addEventListener("change", reset);
					input.addEventListener("keyup", reset);




			});


			</script>

{% endblock extrat_js %}