contacts/urls.py
from django.urls import path, re_path


from .views import (
		contact, emplacement,

			)

app_name = "contacts"





urlpatterns = [

	     path("contact/", contact, name="contact"),
	     path("emplacement/", emplacement, name="emplacement"),






]

flex/urls.py
from django.urls import re_path, path

from .views import (

			about,
			GenerateLesCodePdf
			)








app_name = "flex"





urlpatterns = [

		path("about", about, name="about"),



		]

ylla_consulting/urls.py
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

urlpatterns = [
    path('yalla-consulting-admin/', admin.site.urls),

        path('account/', include("accounts.urls", namespace="accounts")),
        path('accounts/', include("accounts.passwords.urls", namespace="passwords")),




    # Pour wagtail
        re_path(r'^admin/', include(wagtailadmin_urls)),
        re_path(r'^documents/', include(wagtaildocs_urls)),
]



if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    re_path(r"", include(wagtail_urls)),
]

contacts/models.py
from django.db import models

# Create your models here.


class Contact(models.Model):
    nom = models.CharField("Nom", max_length=255)
    prenom = models.CharField("Prénom", max_length=255)
    email  = models.EmailField("Email")
    type_contact = models.CharField("Type", max_length=255)
    sujet  = models.CharField("Sujet", max_length=255)
    message = models.TextField()
    timestamp   = models.DateTimeField("Création", auto_now_add=True)
    updated     = models.DateTimeField("Modification", auto_now=True)
    contact_document_pdf = models.FileField(upload_to="rdv_pp_document", null=True, blank=True)


    class Meta:
        verbose_name = "Contact"
        verbose_name_plural = "Contacts"
        ordering = ["-timestamp", "-updated"]

contacts/forms.py
from django import forms


from captcha.fields import ReCaptchaField, ReCaptchaV3


from .models import Contact



class ContactForm(forms.ModelForm):
    captcha = ReCaptchaField(
    widget=ReCaptchaV3(
        attrs={
            'required_score':0.95,
        }
        )
    )
    class Meta:
        model = Contact
        fields = ["prenom", "nom", "email", "sujet", "message"]

        widgets = {
            "prenom": forms.TextInput(
            attrs = {
            # "class": "form-control input-sm",
            "placeholder": "Votre prénom",


            }
            ),
        	"nom": forms.TextInput(
					attrs = {
						# "class": "form-control input-sm",
                        "placeholder": "Votre nom",

					}
			),

			"email": forms.EmailInput(
					attrs = {
						# "class": "form-control input-sm",
                        "placeholder": "E-Mail",


					}
			),


            "sujet": forms.TextInput(
            attrs = {
            # "class": "form-control input-sm",
            "placeholder": "Sujet",


            }
            ),
        	"message": forms.Textarea(
					attrs = {
						# "class": "form-control input-sm",
                        "placeholder": "Votre message",

					}
			),

        }

contacts/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from email.mime.base import MIMEBase
from io import BytesIO

from email import encoders

from django.conf import settings

from django.core.mail import  EmailMessage, send_mail

from django.contrib import messages

from utils.pdf_render import render_to_pdf

from .forms import ContactForm
# Create your views here.


def contact(request):
    selection_type = request.POST.get("type_contact")
    print("La selection est:", selection_type)
    context = {}
    form = ContactForm(request.POST or None)
    if form.is_valid() and selection_type is not None:
        instance = form.save(commit=False)
        instance.type_contact = selection_type
        context["models_instance"] = instance
        contact_pdf = render_to_pdf("contacts/pj/contact_pdf.html", context)
        filename = """Prise de contact {prenom} {nom}.pdf""".format(prenom=instance.prenom, nom=instance.nom)
        instance.contact_document_pdf.save(filename,BytesIO(contact_pdf.content))
        subject = "Prise de contact de la part de {prenom} {nom}".format(prenom=instance.prenom, nom=instance.nom)

        with open(settings.BASE_DIR / "contacts/templates/contacts/pj/contact_pj_message.txt") as f:
            contact_pj_message = f.read()

        from_email = settings.EMAIL_HOST_USER
        to_email = ["ambaguirabatrdv@gmail.com", "bnvnmmnl@gmail.com",]


        email_to_staff = EmailMessage(
        subject = subject,
        body= contact_pj_message,
        from_email= from_email,
        to= to_email,)
        email_attachment = MIMEBase('application', "octet-stream")
        email_attachment.set_payload(instance.contact_document_pdf.read())
        encoders.encode_base64(email_attachment)
        email_attachment.add_header("Content-Disposition", "attachment", filename="{prenom}_{nom}.pdf".format(prenom= instance.prenom, nom=instance.nom))

        email_to_staff.attach(email_attachment)
        email_to_staff.send()
        messages.success(request, "Message envoyé avec succès")
        return redirect(reverse("rdv:services"))

    else:
        print("Non valide")
    context = {"form": form}

    return render(request, "contacts/contact.html", context)



def emplacement(request):
    context = {}

    return render(request, "contacts/emplacement.html", context)

contacts/templates/contacts/contact.html
{% extends "base.html" %}

{% load static wagtailcore_tags wagtailroutablepage_tags pages_url_extras   wagtailimages_tags wagtailroutablepage_tags cache %}




{% block content %}

    <div class="page-wrapper">

        <section class="page-header" style="background-image: url({% static 'images/gn/flag.jpg' %}); background-repeat: repeat;">
            <div class="container">
                <h2>Contactez </h2>
            </div><!-- /.container -->
        </section><!-- /.page-header -->
        <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                         {% if messages %}
                                {% for message in messages %}
                                    {% if message.tags == 'success' %}
                                        <div class="alert alert-success">{{ message }}</div>
                                    {% elif message.tags == 'error' %}
                                        <div class="alert alert-danger">{{ message }}</div>
                                    {% endif %}
                                {% endfor %}
                         {% endif %}
                    </div>
                </div>
        </div>

        <div class="contact-one">
            <div class="container">
                <div class="block-title-two text-center">
                    <p>Contact</p>
                    <h3>Ambassade de la République au Royaume du Maroc</h3>
                </div><!-- /.block-title-two -->
                <div class="row">
                    {% include "rdv/snippets/address_sidebar.html" %}

                    <div class="col-lg-8">
                        <form action="{% url 'contacts:contact' %}" method="post" class="contact-form-validated contact-one__form">
                            {% csrf_token %}
                            <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            {% if form.errors %}
                                                {% for field in form %}
                                                    {% for error in field.errors %}
                                                        <div class="alert alert-danger">
                                                            <strong>{{ error|escape }}</strong>
                                                        </div>
                                                    {% endfor %}
                                                {% endfor %}
                                                {% for error in form.non_field_errors %}
                                                    <div class="alert alert-danger">
                                                        <strong>{{ error|escape }}</strong>
                                                    </div>
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                    </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    {{ form.prenom }}
                                </div><!-- /.col-lg-6 -->
                                <div class="col-lg-6">
                                    {{ form.nom }}

                                </div><!-- /.col-lg-6 -->
                                <div class="col-lg-6">
                                    {{ form.email }}

                                </div><!-- /.col-lg-6 -->
                                <div class="col-lg-6">
                                    <select title="Contact pour" name="type_contact" class="selectpicker" required>
                                        <!-- <option value="#">Contact pour</option> -->
                                        <option value="Prise de renseignement">Prise de renseignement</option>
                                        <option value="Déclaration de perte">Delacaration de perte</option>
                                        <option value="Autres">Autres</option>
                                    </select><!-- /#.selectpicker -->
                                </div><!-- /.col-lg-6 -->
                                <div class="col-lg-12">
                                    {{ form.sujet }}

                                </div><!-- /.col-lg-6 -->
                                <div class="col-lg-12">

                                    {{ form.message }}

                                </div><!-- /.col-lg-12 -->

                                <div class="col-lg-12">

                                    {{ form.captcha }}

                                </div><!-- /.col-lg-12 -->

                                <div class="col-lg-12">
                                    <button class="thm-btn contact-one__btn" type="submit">Envoyer</button>
                                </div><!-- /.col-lg-12 -->
                            </div><!-- /.row -->
                        </form><!-- /.contact-one__form -->
                    </div><!-- /.col-lg-8 -->
                </div><!-- /.row -->
            </div><!-- /.container -->
        </div><!-- /.contact-one -->

        {% include "rdv/snippets/g_maps.html" %}

        <section class="cta-one" style="background-image: url({% static 'assets/images/shapes/cta-bg-1-1.jpg' %});">
            <div class="container text-center">
                <h3>Sachez que!</h3>
                <p>
                    Nous répondrons dès que possible
                </p>

                <!-- /.cta-one__btn-block -->
            </div>
            <!-- /.container -->
        </section>

    </div><!-- /.page-wrapper -->


    {% endblock content %}

contacts/templates/contacts/emplacement.html
{% extends "base.html" %}

{% load static wagtailcore_tags wagtailroutablepage_tags pages_url_extras   wagtailimages_tags wagtailroutablepage_tags cache %}




{% block content %}

    <div class="page-wrapper">

        <section class="page-header" style="background-image: url({% static 'images/gn/flag.jpg' %}); background-repeat: repeat;">
            <div class="container">
                <h2>Emplacement de l'ambassade de la République de Guinée au Royaume du Maroc </h2>
            </div><!-- /.container -->
        </section><!-- /.page-header -->

        {% include "rdv/snippets/g_maps.html" %}

    </div><!-- /.page-wrapper -->


    {% endblock content %}